# Generated by Django 5.2.6 on 2025-10-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplicationdocument_ai_analysis_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='vehicle_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='vehicle_vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='vehicle_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
