# Generated by Django 5.2.6 on 2025-10-07 12:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def forwards_normalize(apps, schema_editor):
    LoanApplication = apps.get_model('loans', 'LoanApplication')
    ApplicantPersonalInfo = apps.get_model('loans', 'ApplicantPersonalInfo')
    ApplicantIdentification = apps.get_model('loans', 'ApplicantIdentification')
    ApplicantFinancialProfile = apps.get_model('loans', 'ApplicantFinancialProfile')
    ApplicantAddress = apps.get_model('loans', 'ApplicantAddress')
    VehicleInformation = apps.get_model('loans', 'VehicleInformation')

    for application in LoanApplication.objects.all():
        personal_info = ApplicantPersonalInfo.objects.create(
            first_name=application.first_name,
            last_name=application.last_name,
            email=application.email,
            phone=application.phone,
            dob=application.dob,
            social_security=getattr(application, 'social_security', None),
            banks_name=getattr(application, 'banks_name', None),
        )

        identification_info = ApplicantIdentification.objects.create(
            personal_info=personal_info,
            identification_type=getattr(application, 'identification_type', None),
            id_issuing_agency=getattr(application, 'id_issuing_agency', None),
            identification_no=getattr(application, 'identification_no', None),
        )

        financial_profile = ApplicantFinancialProfile.objects.create(
            income=getattr(application, 'income', None),
            employment_status=getattr(application, 'employment_status', 'employed'),
            employment_length=getattr(application, 'employment_length', None),
            income_source=getattr(application, 'income_source', None),
            gross_monthly_income=getattr(application, 'gross_monthly_income', None),
            pay_frequency=getattr(application, 'pay_frequency', None),
            next_pay_date=getattr(application, 'next_pay_date', None),
            last_pay_date=getattr(application, 'last_pay_date', None),
            active_bankruptcy=getattr(application, 'active_bankruptcy', None),
            direct_deposit=getattr(application, 'direct_deposit', None),
            military_status=getattr(application, 'military_status', None),
        )

        address = ApplicantAddress.objects.create(
            street=getattr(application, 'street', ''),
            city=getattr(application, 'city', ''),
            state=getattr(application, 'state', ''),
            zip_code=getattr(application, 'zip_code', ''),
        )

        vehicle_info = VehicleInformation.objects.create(
            make=getattr(application, 'vehicle_make', None),
            model=getattr(application, 'vehicle_model', None),
            year=getattr(application, 'vehicle_year', None),
            vin=getattr(application, 'vehicle_vin', None),
            mileage=getattr(application, 'vehicle_mileage', None),
            color=getattr(application, 'vehicle_color', None),
            license_plate=getattr(application, 'license_plate', None),
            registration_state=getattr(application, 'registration_state', None),
        )

        application.personal_info = personal_info
        application.identification_info = identification_info
        application.financial_profile = financial_profile
        application.address = address
        application.vehicle_info = vehicle_info
        application.save(update_fields=['personal_info', 'identification_info', 'financial_profile', 'address', 'vehicle_info'])


def noop_reverse(apps, schema_editor):
    # Irreversible migration (fields dropped)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loanapplication_credit_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['zip_code'], name='loans_appli_zip_cod_9493a8_idx'),
                    models.Index(fields=['city', 'state'], name='loans_appli_city_0c689b_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ApplicantFinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(20000)])),
                ('employment_status', models.CharField(blank=True, choices=[('employed', 'Employed'), ('self-employed', 'Self-Employed'), ('retired', 'Retired'), ('unemployed', 'Unemployed')], default='employed', max_length=20)),
                ('employment_length', models.DecimalField(blank=True, decimal_places=1, help_text='Employment length in years', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('income_source', models.CharField(blank=True, help_text='Employer/Income Source', max_length=255, null=True)),
                ('gross_monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pay_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('next_pay_date', models.DateField(blank=True, null=True)),
                ('last_pay_date', models.DateField(blank=True, null=True)),
                ('active_bankruptcy', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('direct_deposit', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('military_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('social_security', models.CharField(blank=True, help_text='Format: XXX-XX-XXXX', max_length=11, null=True)),
                ('banks_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['email'], name='loans_appli_email_7b75bc_idx'),
                    models.Index(fields=['phone'], name='loans_appli_phone_d482f5_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='VehicleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('vin', models.CharField(blank=True, max_length=17, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_state', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_type', models.CharField(blank=True, max_length=50, null=True)),
                ('id_issuing_agency', models.CharField(blank=True, max_length=100, null=True)),
                ('identification_no', models.CharField(blank=True, max_length=100, null=True)),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identification', to='loans.applicantpersonalinfo')),
            ],
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='personal_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_application', to='loans.applicantpersonalinfo'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='identification_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_application', to='loans.applicantidentification'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='financial_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_application', to='loans.applicantfinancialprofile'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_application', to='loans.applicantaddress'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='vehicle_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_application', to='loans.vehicleinformation'),
        ),
        migrations.RunPython(forwards_normalize, noop_reverse),
        migrations.RemoveIndex(
            model_name='loanapplication',
            name='loans_loana_email_b7f88d_idx',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='active_bankruptcy',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='banks_name',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='city',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='direct_deposit',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='employment_length',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='gross_monthly_income',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='id_issuing_agency',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='identification_no',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='identification_type',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='income',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='income_source',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='last_pay_date',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='military_status',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='next_pay_date',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='pay_frequency',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='registration_state',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='social_security',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='state',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='street',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='vehicle_mileage',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='vehicle_vin',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='vehicle_year',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='zip_code',
        ),
    ]
