# Generated by Django 5.2.6 on 2025-10-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_loanapplication_signature_signed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='ai_analysis_data',
            field=models.JSONField(blank=True, help_text='Full AI analysis response from Gemini', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ai_analysis_timestamp',
            field=models.DateTimeField(blank=True, help_text='When AI analysis was performed', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ai_approval_suggestion',
            field=models.CharField(blank=True, choices=[('approve', 'Approve'), ('conditional', 'Conditional Approval'), ('review', 'Needs Review'), ('reject', 'Reject')], help_text='AI suggestion for approval decision', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ai_recommendation',
            field=models.TextField(blank=True, help_text='AI-generated recommendation for loan approval', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ai_risk_assessment',
            field=models.CharField(blank=True, choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('very_high', 'Very High Risk')], help_text='AI-assessed risk level', max_length=20, null=True),
        ),
    ]
