# Generated by Django 5.2.6 on 2025-10-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_loanapplication_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, help_text="Store any additional form fields that don't fit in normalized structure"),
        ),
    ]
