# Generated by Django 5.2.6 on 2025-10-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanapplication_vehicle_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='active_bankruptcy',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='banks_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='direct_deposit',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='gross_monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='id_issuing_agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='identification_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='identification_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='income_source',
            field=models.CharField(blank=True, help_text='Employer/Income Source', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='last_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='military_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='next_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='pay_frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='photo_borrower',
            field=models.FileField(blank=True, null=True, upload_to='loan_documents/borrower/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='photo_front_car',
            field=models.FileField(blank=True, null=True, upload_to='loan_documents/car_front/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='photo_insurance',
            field=models.FileField(blank=True, null=True, upload_to='loan_documents/insurance/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='photo_license',
            field=models.FileField(blank=True, null=True, upload_to='loan_documents/license/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='photo_odometer',
            field=models.FileField(blank=True, null=True, upload_to='loan_documents/odometer/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='photo_vin',
            field=models.FileField(blank=True, null=True, upload_to='loan_documents/vin_plate/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='photo_vin_sticker',
            field=models.FileField(blank=True, null=True, upload_to='loan_documents/vin/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='registration_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='social_security',
            field=models.CharField(blank=True, help_text='Format: XXX-XX-XXXX', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
