# Generated by Django 5.2.6 on 2025-10-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanapplication_active_bankruptcy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='applicant_estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Applicant's own estimate of vehicle value", max_digits=12, null=True),
        ),
    ]
