# Generated by Django 5.2.6 on 2025-10-07 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_add_applicant_estimated_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='credit_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('self-employed', 'Self-Employed'), ('retired', 'Retired'), ('unemployed', 'Unemployed')], default='employed', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(20000)]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='term',
            field=models.IntegerField(blank=True, default=36, help_text='Loan term in months', null=True, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(72)]),
        ),
    ]
