# Generated by Django 5.2.6 on 2025-10-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_loanapplication_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('query', 'Query'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
    ]
