# Generated by Django 5.2.6 on 2025-11-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_alter_loanapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='photo_borrower',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='photo_front_car',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='photo_insurance',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='photo_license',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='photo_odometer',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='photo_vin',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='photo_vin_sticker',
        ),
        migrations.AlterField(
            model_name='loanapplicationdocument',
            name='document_type',
            field=models.CharField(choices=[('id', 'ID Document'), ('income', 'Income Verification'), ('address', 'Address Proof'), ('vehicle_title', 'Vehicle Title'), ('photo_vin_sticker', 'VIN Sticker Photo'), ('photo_odometer', 'Odometer Photo'), ('photo_borrower', 'Borrower Photo'), ('photo_front_car', 'Front of Car Photo'), ('photo_vin_plate', 'VIN Plate Photo'), ('photo_license', 'License Photo'), ('photo_insurance', 'Insurance Photo'), ('other', 'Other')], max_length=20),
        ),
    ]
