# Generated by Django 5.2.6 on 2025-11-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_remove_loanapplication_photo_borrower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantpersonalinfo',
            name='social_security',
            field=models.CharField(blank=True, help_text='Social Security Number', max_length=50, null=True),
        ),
    ]
